<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sorry! This function is not avaiable in the means time, please try again later!</title>
<link rel="stylesheet" href="/stylesheet/app.css"/>
</head>

<body>
<cfoutput>
<h2>Sorry! This function is not avaiable in the means time, please try again later!</h2>
<p>
The above problem may occured as the following reason:
<ul>
<li>The server is busy at the moment</li>
<li>System is under upgrading process</li>
<li>Uncompactible browser setting toward the system</li>
<li>Wrong data input or usage of the system</li>
</ul>
Please try again later! If the problem persist, please dont hesistate to contact us at shicai@mynetiquette.com.
</p>
Click <a href="#form.httpRefferer#" >HERE</a> to go back the page
</cfoutput>
</body>
<cfmail from="noreply@mynetiquette.com" to="#form.mailto#" subject="Error detect on the payroll system" type="html">

<p>Dear Sir,</p>
<p>Error below has occur while payroll system is operate by the personal below</p>
<table border="1">
<tr>
<td width="100px">Username</td>
<td width="5px">:</td>
<td width="300px">#HUserName#</td>
</tr>
<tr>
<td>Company Id</td>
<td>:</td>
<td>#HcomID#</td>
</tr>
<tr>
<td>Diagnostics</td>
<td>:</td>
<td>#form.diag#</td>
</tr>
<tr>
<td>Date Occured</td>
<td>:</td>
<td>#form.date#</td>
</tr>
<tr>
<td>Browser used</td>
<td>:</td>
<td>#form.browser#</td>
</tr>
<tr>
<td>IP address</td>
<td>:</td>
<td>#form.ipadd#</td>
</tr>
<tr>
<td>Http Refferer</td>
<td>:</td>
<td>#form.httpRefferer#</td>
</tr>
<tr>
<td>Generated Page</td>
<td>:</td>
<td>#form.generated#</td>
</tr>
<tr>
<td>Query String</td>
<td>:</td>
<td>#form.query#</td>
</tr>

</table>
<br />
<br />

From: Netiquette Payroll System<br />
Company ID: #HcomID#
</p>
<p style="font-size:smaller">This email is auto generated by system. Please do not reply to this email.</p>
</cfmail>
</html>
